version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lwapi.walkingmask.tk:latest
    container_name: lwapi.walkingmask.tk
    restart: always
    environment:
      VIRTUAL_HOST: lwapi.walkingmask.tk
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: lwapi.walkingmask.tk
      LETSENCRYPT_EMAIL: walkingmask@gmail.com
    expose:
      - 8080
    volumes:
      - ./app:/app
    working_dir: /app
    init: true
    command: uvicorn main:app --no-access-log --host 0.0.0.0 --port 8080
    logging:
      driver: fluentd
      options:
        cache-disabled: "true"
        tag: "docker.service"
        fluentd-async-connect: "true"

networks:
  default:
    external:
      name: nginx-proxy-shared